### ISSUE TITLE
Is there a stable (non-beta version) of vcluster-hostpath-mapper for vcluster OSS?

### ISSUE THREAD

**Issue by joaocc** [loft-sh/vcluster-hostpath-mapper#9]
Hi,
Is there any non-beta version of vcluster-hostpath-mapper?
Is the current latest beta a stable version?
While we understand that the focus seems to be on the paid version (central hostpath mapper) of vcluster-pro, it would still be interesting to have a stable version to support vcluster OSS.
Thanks

**Comment by ishankhare07** [comment]
@joaocc , we have now - [v0.1.0](https://github.com/loft-sh/vcluster-hostpath-mapper/releases/tag/v0.1.0) 🙂

**Comment by joaocc** [comment]
Perfect. Thanks!
